version: "2"
services:
    backend:
        container_name: boilerplate_server
        build: .
        restart: always
        environment:
            - DB_URI=mongodb://mongo:27017/boilerplate_db
        volumes: 
            - ".:/app"
        ports:
            - "5000:5000"
        links:
            - mongo
    mongo:
        container_name: boilerplate_db
        image: mongo
        ports:
            - "27017:27017"
        


